disabled_rules: 
  - cyclomatic_complexity
  - compiler_protocol_init
  - force_cast
  - colon
  - comma
  - control_statement
  - identifier_name
opt_in_rules:
  - empty_count
included: 
  - Attributed
line_length: 150
file_length:
  warning: 500
  error: 1200
reporter: "xcode" 
