#
# Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
#
lane :beta do |values|
  # Fabric generated this lane for deployment to Crashlytics Beta
  # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
  #update_project_codesigning(path: "GoCard.xcodeproj",use_automatic_signing: false)
  gym(scheme: 'GoCard', export_method: 'development', clean:true, silent: true, use_legacy_build_api:true)

  emails = values[:test_email] ? values[:test_email] : ['nhnam.develop@gmail.com','nuttasorn.k@gocardofficial.com'] # You can list more emails here
  groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

  crashlytics(api_token: '02bfb35b35cf8a8d432050b5b490bd19bd4f3544',
           build_secret: '8e85a2d60406ff4675ac4fc0005aa5ccb3307ebe5a0c703c7841f7d77a20699f',
                 emails: emails,
                 groups: groups,
                  notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
          notifications: true) # Should this distribution notify your testers via email?

  # for all available options run `fastlane action crashlytics`

  # You can notify your team in chat that a beta build has been uploaded
  # slack(
  #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
  #   channel: "beta-releases",
  #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
  # )
end
